// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgIO_uQvrK-AMy2L8__6vSII04Zb8KT8',
    appId: '1:904959021524:web:1cb04bf6df9cf3ffc0c641',
    messagingSenderId: '904959021524',
    projectId: 'takeaway-aea0e',
    authDomain: 'takeaway-aea0e.firebaseapp.com',
    storageBucket: 'takeaway-aea0e.appspot.com',
    measurementId: 'G-JVEY4VD43E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXY_zhoy3YgFp_oo8eXBQFg9vNrA_A1Og',
    appId: '1:904959021524:android:f02daf6f24b74954c0c641',
    messagingSenderId: '904959021524',
    projectId: 'takeaway-aea0e',
    storageBucket: 'takeaway-aea0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6nrOt7x5L7gT-JuojZw3OdHEFiXpVxo',
    appId: '1:904959021524:ios:574937d41ca1ba22c0c641',
    messagingSenderId: '904959021524',
    projectId: 'takeaway-aea0e',
    storageBucket: 'takeaway-aea0e.appspot.com',
    iosClientId: '904959021524-o8ij8mg6hpaul194bhlsu15kuen4kdo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN6nrOt7x5L7gT-JuojZw3OdHEFiXpVxo',
    appId: '1:904959021524:ios:574937d41ca1ba22c0c641',
    messagingSenderId: '904959021524',
    projectId: 'takeaway-aea0e',
    storageBucket: 'takeaway-aea0e.appspot.com',
    iosClientId: '904959021524-o8ij8mg6hpaul194bhlsu15kuen4kdo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
